### PR TITLE
Adding Neha to the project

### PR DESCRIPTION
**Pull request by nehakgoyal**
Creating pull request for Neha

### CODE REVIEW

**Comment by PeterBell** [comment]
Hey @nehakgoyal could you add your favorite city to this?

**Comment by nehakgoyal** [comment]
I will add my favorite city

**Comment by PeterBell** [comment]
LGTM 👍  lets's 🚢 it!

**Comment by PeterBell** [comment]
👍 🔢 🐑 🍔 🔨 🐹 ✋

**Pull request merged**
